version: "3.8"

services:
  pymavlink:
    build: .
    volumes:
      - ./data:/root/pymavlink
      - ./vscode-server:/root/.vscode-server
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    network_mode: "host"
