version: '3.7'

services:
  debian_ros2_humble:
    image: docker.aerial-edge.no/debian_ros2_humble:1.0.0
    container_name: debian_ros2_humble_container
    network_mode: host
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - ./ros_workspace:/home/ros/ros_workspace
    command: >
      /bin/bash -c "git clone https://github.com/your-repo/your_ros2_project.git /home/ros/ros_workspace/src/your_ros2_project &&
                    source /opt/ros/humble/setup.bash &&
                    colcon build --symlink-install &&
                    source /home/ros/ros_workspace/install/setup.bash &&
                    ros2 run your_ros2_package your_ros2_node"
